### ISSUE TITLE
ability to export recipe to PDF?? 

### ISSUE THREAD

**Issue by bamohan** [katharinap/my_recipes#49]

**Comment by katharinap** [comment]
I found a nice gem for this, wicked_pdf (https://github.com/mileszs/wicked_pdf).  I gave it a try today and it seems to work quite nicely.  I haven't done any styling yet (only changed h1 to green to see if the css works at all).  Could you give it a try and let me know what you think?  I added branch 49-create-pdf.

The gem depends on a binary.  There are gems to get this to work.  For me, the heroku specific gem works.  It's possible that it only works because I have ubuntu on my laptop.  If you have problems, we might have to use wkhtmltopdf-binary-edge (https://github.com/pallymore/wkhtmltopdf-binary-edge) for non-production environments instead of wkhtmltopdf-heroku (https://github.com/rposborne/wkhtmltopdf-heroku).
