### ISSUE TITLE
 Save all the 'Directions' in a single row?? 

### ISSUE THREAD

**Issue by bamohan** [katharinap/my_recipes#63]
i.e. without 'idx' column for each?? 

Update and add will become so much easier

**Comment by katharinap** [comment]
Do you want to store the directions as text attribute in the recipes table directly instead of the has_many association?  I implemented it the way it currently is because I thought it might be nice to add a picture for a step.  To be honest, I haven't had any recipe so far for which I actually wanted to do that.  So maybe that's unnecessary overhead.  Having a simple text attribute instead seems much cleaner to me now.  So I'm OK with that change (if that's really what you meant) and I can also take care of that unless you want to do it.

**Comment by bamohan** [comment]
Hi Kat! I tried editing a recipe and I found the method of editing line by line a bit cumbersome. It might be easier to just store it as one field with line breaks. That will be great if you can take care of it. I doubt I will have time any time soon to do this. Thanks!!
